name: Update cards
on:
  schedule:
    - cron: "0 14 * * *"
jobs:
  updateCards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: node ./scripts/downloadCards.js
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
